name: yacut workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        script: |
          touch .env
          echo DATABASE_URI=${{ secrets.DATABASE_URI }} >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return
        pip install -r requirements.txt
    - name: Test with flake8 and pytests
      run: |
        python -m flake8